# Generated by Django 3.0.5 on 2021-09-24 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('file_content', models.FileField(upload_to='image_host', verbose_name='content')),
            ],
        ),
    ]
