# Generated by Django 3.0.5 on 2021-09-25 05:29

import ImageHost.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ImageHost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='createTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updateTime'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file_content',
            field=models.FileField(upload_to=ImageHost.models.on_upload, verbose_name='content'),
        ),
    ]
