# Generated by Django 3.0.5 on 2020-11-18 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('file_content', models.FileField(upload_to='', verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
            ],
        ),
    ]
