# Generated by Django 3.0.5 on 2020-11-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxfile',
            name='file_content',
            field=models.FileField(upload_to='box_files', verbose_name='content'),
        ),
    ]
