# Generated by Django 3.0.5 on 2021-01-14 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0002_auto_20201126_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxFileArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('area_name', models.CharField(max_length=120, verbose_name='areaName')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('need_password', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='boxfile',
            name='box_file_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Box.BoxFileArea'),
        ),
    ]
