# Generated by Django 3.0.5 on 2021-10-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=256)),
                ('committer', models.CharField(max_length=64)),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
