# Generated by Django 3.0.5 on 2021-10-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='qa_checked',
            field=models.CharField(default='', max_length=64),
        ),
    ]
