# Generated by Django 3.0.5 on 2021-10-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_gitcommit_qa_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommit',
            name='ref',
            field=models.CharField(default='', max_length=256),
        ),
    ]
