# Generated by Django 2.1.7 on 2020-11-17 08:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststruct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='createTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststruct',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateTime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teststruct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
