# Generated by Django 3.0.5 on 2020-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestAPI', '0002_auto_20201117_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststruct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createTime'),
        ),
        migrations.AlterField(
            model_name='teststruct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updateTime'),
        ),
    ]
